server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://myemployeedb.ccuxnrcbeumx.us-east-1.rds.amazonaws.com/employee_dir
    username: admin
    password: myemployeepd
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:mysql://localhost:3306/employee_dir
#    username: springstudent
#    password: springstudent
#    driverClassName: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
  jwt:
    secret: f56ccf8e79ced26f9bee60ea49ed528924eb7a7d2a7d07cff410616ae03e6f02
management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always